spring:
  datasource:
    url: jdbc:mysql://192.168.1.106:3306/saas-dev?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: saasdev
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
      host: 192.168.1.106
      port: 6379
      database: 5
  activiti: 
    database-schema: saasdev
logging: 
  level:
    com.len.mapper: DEBUG
    org.activiti.engine.impl.persistence.entity: trace
feign:
  file-service: https://maya-plugin-oss-demo.ystyun.com
trademConfig: 
  printUrl: http://192.168.5.10:8080 
  wxUrl:  
  jpushUrl: https://h5-test.ystyun.com/view/message/navigationMenu?source=app
  saleScontractTemplateId: 